// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owvzklokxyofgjvferqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93dnprbG9reHlvZmdqdmZlcnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjMyMjQsImV4cCI6MjA2OTM5OTIyNH0.oFzzHILrPbNZMgsPDN3CelSHOhx09DNtO5Dvrk4uqIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});